---
driver:
  name: docker
  require_chef_omnibus: false
  provision_command: curl -L https://www.opscode.com/chef/install.sh | bash

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags

platforms:
  - name: centos-6.5
  - name: ubuntu-12.04
  - name: debian-7.8

suites:
  - name: user
    run_list:
      - recipe[gemrc_test::user]
  - name: system
    run_list:
      - recipe[gemrc_test::system]
  - name: command_options
    run_list:
      - recipe[gemrc_test::command_options]
